[Theme]
Current=nord-light

[Autologin]
Relogin=false
Session=
User=

[General]
HaltCommand=
RebootCommand=
DisplayServer=wayland
Greeter.Session=greeter.desktop


[Users]
MaximumUid=60000
MinimumUid=1000
