[DeviceInfo]
deviceName=Airpods Pro 2
hearingAidEnabled=false
magicAccEncKey=@ByteArray(\xcf\x1l\xf6\x83p{&_\xe6\xfa\xdb^\x7fwr)
magicAccIRK=@ByteArray(>\xa3\x80R\v\b\xf5\x99\xc4w\xf3\xe9\xb3\xe9\xc6\xdb)
model=6

[crossdevice]
enabled=true
